name: json_api_document
description: JSON API Document model
version: 0.0.4
author: Alexey Karapetov <karapetov@gmail.com>
homepage: https://github.com/f3ath/json-api-dart
dev_dependencies:
  test: ^0.12.32
  json_matcher: ^0.1.0
