name: json_api_document
description: JSON API Document model
version: 0.0.8
author: Alexey Karapetov <karapetov@gmail.com>
homepage: https://github.com/f3ath/json-api-dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: "1.3.0"
  json_matcher: ">=0.2.2"
